server:
  error:
    include-stacktrace: on_param
  port: 8080

spring:
  application:
    name: springboot2-essentials
  datasource:
    url: jdbc:mysql://localhost:3306/ms-email?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ********@gmail.com
    password: ********
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  rabbitmq:
    addresses: amqps://ylosbsyc:8v3ebmIQCa654Lrf8dgKRSKx62alsttD@rat.rmq2.cloudamqp.com/ylosbsyc
    queue: ms.email
